// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID      string `json:"id"`
	PostID  string `json:"postId"`
	UserID  bool   `json:"userId"`
	Content string `json:"content"`
}

type Mutation struct {
}

type NewComment struct {
	PostID  string `json:"postId"`
	UserID  string `json:"userId"`
	Content string `json:"content"`
}

type NewPost struct {
	UserID  string `json:"userId"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Post struct {
	ID       string     `json:"id"`
	UserID   string     `json:"userId"`
	Title    string     `json:"title"`
	Content  string     `json:"content"`
	Comments []*Comment `json:"comments"`
}

type Query struct {
}
